import { useState } from 'react'
import { profileDefaults, statLabels } from '../data/profileDefaults'

function ProfileEditor({ character, onSave }) {
  const [profile, setProfile] = useState({ ...profileDefaults, ...character.profile, abilities: character.profile?.abilities || [], stats: { ...profileDefaults.stats, ...character.profile?.stats } })
  const update = (key, value) => setProfile({ ...profile, [key]: value })
  const updateAbility = (index, key, value) => update('abilities', profile.abilities.map((ability, abilityIndex) => abilityIndex === index ? { ...ability, [key]: value } : ability))
  const removeAbility = (index) => update('abilities', profile.abilities.filter((_, abilityIndex) => abilityIndex !== index))
  return <form className="profile-editor" onSubmit={(event) => { event.preventDefault(); onSave(profile) }}>
    <h2>Editar perfil</h2>
    <div className="profile-editor-grid"><label className="field">Título de combate<input value={profile.title} onChange={(event) => update('title', event.target.value)} placeholder={character.name} /></label><label className="field">Frase distintiva<input value={profile.tagline} onChange={(event) => update('tagline', event.target.value)} placeholder="El azote..." /></label><label className="field">Color de acento<input className="color-input" type="color" value={profile.accent} onChange={(event) => update('accent', event.target.value)} /></label><label className="field">Imagen principal (URL)<input type="url" value={profile.primaryImage} onChange={(event) => update('primaryImage', event.target.value)} placeholder="Usa la imagen del personaje si queda vacío" /></label><label className="field full-width">Galería de vistas<input value={profile.galleryImages.join(', ')} onChange={(event) => update('galleryImages', event.target.value.split(',').map((url) => url.trim()).filter(Boolean))} placeholder="URLs separadas por comas (máximo 3)" /></label><label className="field full-width">Biografía<textarea value={profile.bio} onChange={(event) => update('bio', event.target.value)} placeholder="Historia, personalidad o trasfondo..." /></label></div>
    <section className="abilities-editor"><div><h3>Habilidades</h3><button className="button secondary small" onClick={() => update('abilities', [...profile.abilities, { name: '', description: '' }])} type="button">+ Agregar habilidad</button></div>{profile.abilities.length ? <div className="ability-editor-list">{profile.abilities.map((ability, index) => <div className="ability-editor-item" key={index}><label className="field">Nombre<input value={ability.name} onChange={(event) => updateAbility(index, 'name', event.target.value)} placeholder="Nombre de habilidad" /></label><label className="field">Descripción<textarea value={ability.description} onChange={(event) => updateAbility(index, 'description', event.target.value)} placeholder="Qué hace esta habilidad" /></label><button className="remove-ability" onClick={() => removeAbility(index)} type="button" aria-label={`Eliminar habilidad ${index + 1}`}>×</button></div>)}</div> : <p className="profile-editor-empty">Todavía no hay habilidades. Agrégalas una a una.</p>}</section>
    <fieldset className="stats-editor"><legend>Atributos</legend>{Object.entries(statLabels).map(([key, label]) => <label key={key}>{label}<input type="range" min="0" max="6" value={profile.stats[key]} onChange={(event) => update('stats', { ...profile.stats, [key]: Number(event.target.value) })} /><b>{profile.stats[key]}/6</b></label>)}</fieldset>
    <div className="profile-editor-grid"><label className="field">Técnica definitiva<input value={profile.ultimateName} onChange={(event) => update('ultimateName', event.target.value)} /></label><label className="field">Imagen de técnica (URL)<input type="url" value={profile.ultimateImage} onChange={(event) => update('ultimateImage', event.target.value)} /></label><label className="field full-width">Descripción de técnica<textarea value={profile.ultimateDescription} onChange={(event) => update('ultimateDescription', event.target.value)} /></label></div>
    <button className="button" type="submit">Guardar perfil</button>
  </form>
}

export default ProfileEditor
